CREATE DATABASE IF NOT EXISTS `finalweb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `finalweb`;
CREATE TABLE IF NOT EXISTS categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,description TEXT);
CREATE TABLE IF NOT EXISTS products(id INT AUTO_INCREMENT PRIMARY KEY,category_id INT NOT NULL,name VARCHAR(150) NOT NULL,price INT NOT NULL DEFAULT 0,image_url VARCHAR(255) NOT NULL,FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS posts(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,excerpt VARCHAR(255),image_url VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS site_metrics(metric_key VARCHAR(50) PRIMARY KEY,metric_value INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS branches(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,district VARCHAR(120) NOT NULL,address VARCHAR(255) NOT NULL,phone VARCHAR(50) NOT NULL,opening_hours VARCHAR(120) NOT NULL);
CREATE TABLE IF NOT EXISTS slides(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,subtitle VARCHAR(255) NOT NULL,image_url VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS contact_messages(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(150) NOT NULL,phone VARCHAR(50) NULL,subject VARCHAR(150) NULL,reason VARCHAR(80) NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- orders
CREATE TABLE IF NOT EXISTS orders(
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_code VARCHAR(20) NOT NULL UNIQUE,
  customer_name VARCHAR(120) NOT NULL,
  customer_phone VARCHAR(50) NOT NULL,
  customer_email VARCHAR(150) NULL,
  payment_method ENUM('MTN_MOMO','AIRTEL_MONEY') NOT NULL,
  payment_reference VARCHAR(50) NULL,
  status ENUM('pending','awaiting_mobile_money','paid','failed','cancelled') NOT NULL DEFAULT 'pending',
  total_amount INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS order_items(
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NULL,
  name VARCHAR(150) NOT NULL,
  price INT NOT NULL,
  qty INT NOT NULL DEFAULT 1,
  FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
);
